# Generated by Django 3.2.5 on 2021-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
