# Generated by Django 3.2.5 on 2021-07-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_data_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dob',
            field=models.DateField(),
        ),
    ]
