# Generated by Django 3.2.5 on 2021-07-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_data_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dob',
            field=models.DateField(),
        ),
    ]
